name: lemmy_dart_client
description: Dart client for Lemmy API
version: 1.0.0
repository: https://github.com/thunder-app/lemmy_dart_client

environment:
  sdk: ^3.6.0

dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.13
